FROM python:3.11-slim

WORKDIR  /app
COPY requirements.txt .
RUN pip install --no-cahce-dir -r requirements.txt

COPY app ./app
ENV DATA_DIR=/data

CMD ["celery", "-A", "app.workers.celery_app.celery_app", "worker", "--loglevel=INFO", "-Q", "celery"]